name: restaurant_admin
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.17.5 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  flutter_screenutil: 5.5.3+2
  firebase_core: 1.18.0
  cloud_firestore: 3.1.18
  image_picker: 0.8.5+3
  firebase_storage: 10.2.18
  flutter_launcher_icons: 0.9.3
  flutter_native_splash: 2.2.3+1
  grouped_list: 5.1.2
  cached_network_image: 3.2.1
  intl: 0.17.0
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: 2.0.1
  flutter_test: 
    sdk: flutter

flutter_icons:
  image_path: assets/images/app_logo.png
  android: true
  ios: true

flutter_native_splash:
  color: "#ffffff"
  image: assets/images/app_logo.png
  color_dark: "#121212"
  image_dark: assets/images/app_logo.png

  android_12:
    image: assets/images/app_logo.png
    icon_background_color: "#ffffff"
    image_dark: assets/images/app_logo.png
    icon_background_color_dark: "#121212"

  web: false

flutter: 
  assets: 
    - assets/images/
    - assets/fonts/
  fonts: 
    - family: Poppins
      fonts: 
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Medium.ttf
        - asset: assets/fonts/Poppins-Bold.ttf
        - asset: assets/fonts/Poppins-SemiBold.ttf
        - asset: assets/fonts/Poppins-Light.ttf
        - asset: assets/fonts/Poppins-Thin.ttf
        - asset: assets/fonts/Poppins-ExtraLight.ttf
        - asset: assets/fonts/Poppins-ExtraBold.ttf
        - asset: assets/fonts/Poppins-Black.ttf
  uses-material-design: true

